### PR TITLE
[v2] ta: regression: Add test 1036 to test PAuth

### PR DESCRIPTION
**Pull request by ruchi393**
Added the PAuth test in os_test TA as suggested.

Test 1036 is added to test the ARM Security extension
feature PAuth (Pointer Authentication).

Signed-off-by: Ruchika Gupta <ruchika.gupta@linaro.org>

### CODE REVIEW

File: host/xtest/regression_1000.c [hunk 1]
```diff
@@ -2641,3 +2641,50 @@ static void xtest_tee_test_1035(ADBG_Case_t *c)
...
+						NULL, &ret_orig)))
+		return;
+
+	Do_ADBG_BeginSubCase(c, "PAuth NOP test");
+
+	res = TEEC_InvokeCommand(&session, TA_OS_TEST_CMD_PAUTH_NOP, &op,
+				 &ret_orig);
+	if (res == TEEC_ERROR_NOT_SUPPORTED) {
+		Do_ADBG_Log("Binary doesn't support PAuth - skip tests");
+		Do_ADBG_EndSubCase(c, "PAuth NOP test");
```
Comment (jenswi-linaro) [inline host/xtest/regression_1000.c:2666]: Note that this isn't strictly needed, but it doesn't harm either.

File: ta/os_test/pauth_a64.S [hunk 2]
```diff
@@ -0,0 +1,16 @@
+/* SPDX-License-Identifier: BSD-2-Clause */
+/*
+ * Copyright (c) 2022, Linaro Limited
+ */
+
+#include <asm.S>
+
+FUNC corrupt_pac , :
```
Comment (jenswi-linaro) [inline ta/os_test/pauth_a64.S:8]: It could be nice to have the prototype of the C function in a comment above as a reminder of what the caller can expect. Perhaps even a short description of what the function does as I guess most people are not very familiar with the instructions `paciasp` and `autiasp`.

File: ta/os_test/pauth_a64.S [hunk 3]
```diff
@@ -0,0 +1,16 @@
...
+	paciasp
+	/* Flip a random bit in PAC */
```
Comment (jenswi-linaro) [inline ta/os_test/pauth_a64.S:10]: I guess this means "Flip a random bit in PAC field of the return address".

File: ta/os_test/ta_arm_pauth.c [hunk 4]
```diff
@@ -0,0 +1,52 @@
...
+			&implemented);
+	if (res != TEE_SUCCESS)
+		return res;
+
+	if (!implemented)
+		return TEE_ERROR_NOT_SUPPORTED;
+
+	/* Check if PAC instruction generates the authentication code */
+	for (int i = 0; i < 10; i++) {
+		asm volatile("paciza %0 " : "+r" (ptr));
```
Comment (jenswi-linaro) [inline ta/os_test/ta_arm_pauth.c:36]: Please avoid inline assembly mixed with the code. I guess there's not much generic use of this instruction so putting at some common place might not be needed, but perhaps in a separate function above.
By the way, what is this trying to do? Just reading the description of the instruction in the reference manual still leaves some questions.

File: ta/os_test/pauth_a64.S (hunk 2 above)
Comment (ruchi393) [reply ta/os_test/pauth_a64.S:8]: Sure, will add

File: ta/os_test/pauth_a64.S (hunk 3 above)
Comment (ruchi393) [reply ta/os_test/pauth_a64.S:10]: Yes.

File: ta/os_test/ta_arm_pauth.c (hunk 4 above)
Comment (ruchi393) [reply ta/os_test/ta_arm_pauth.c:36]: Pointer authentication requires an address, modifier and key.
paczia Rd
With paczia the address is in the register Rd, modifier is 0 and key is APIAKEY
The instruction will generate and insert pointer authentication code on address specified in Rd with  modifier 0 and key A. The PAC is inserted in Rd itself.

File: host/xtest/regression_1000.c [hunk 5]
```diff
@@ -2641,3 +2641,50 @@ static void xtest_tee_test_1035(ADBG_Case_t *c)
...
+		goto out;
+	}
+
+	if (!ADBG_EXPECT_TEEC_SUCCESS(c, res))
+		goto out;
```
Comment (etienne-lms) [inline host/xtest/regression_1000.c:2671]: missing call to `Do_ADBG_EndSubCase()`

File: host/xtest/regression_1000.c [hunk 6]
```diff
@@ -2641,3 +2641,50 @@ static void xtest_tee_test_1035(ADBG_Case_t *c)
...
+
+	Do_ADBG_EndSubCase(c, "PAuth NOP test");
+
+	Do_ADBG_BeginSubCase(c, "PAuth PAC corruption");
+
+	res = TEEC_ERROR_TARGET_DEAD;
+	(void)ADBG_EXPECT_TEEC_RESULT(c, res,
```
Comment (etienne-lms) [inline host/xtest/regression_1000.c:2678]: minor suggestion:
```c
	ADBG_EXPECT_TEEC_RESULT(c, TEEC_ERROR_TARGET_DEAD,
			TEEC_InvokeCommand(...));

	ADBG_EXPECT_TEEC_ERROR_ORIGIN(c, TEEC_ORIGIN_TEE, ret_orig);

File: host/xtest/regression_1000.c [hunk 7]
```diff
@@ -2641,3 +2641,50 @@ static void xtest_tee_test_1035(ADBG_Case_t *c)
...
+					   &op, &ret_orig));
+
+	(void)ADBG_EXPECT_TEEC_ERROR_ORIGIN(c, TEEC_ORIGIN_TEE, ret_orig);
+
+	Do_ADBG_EndSubCase(c, "PAuth PAC corruption");
+
+out:
+	TEEC_CloseSession(&session);
+}
+ADBG_CASE_DEFINE(regression, 1036, xtest_tee_test_1036, "Test PAuth (Pointer Authentication)");
```
Comment (etienne-lms) [inline host/xtest/regression_1000.c:2690]: add a line break:
```c
ADBG_CASE_DEFINE(regression, 1036, xtest_tee_test_1036,
		 "Test PAuth (Pointer Authentication)");

File: ta/os_test/ta_arm_pauth.c [hunk 8]
```diff
@@ -0,0 +1,52 @@
+/* SPDX-License-Identifier: BSD-2-Clause */
+/*
+ * Copyright (c) 2022, Linaro Limited
+ * All rights reserved.
```
Comment (etienne-lms) [inline ta/os_test/ta_arm_pauth.c:4]: remove this line or move at end of previous line

File: host/xtest/regression_1000.c (hunk 5 above)
Comment (jenswi-linaro) [reply host/xtest/regression_1000.c:2671]: As I said above, this isn't strictly needed.

The test framework automatically ends all started subcases when the main test case is done.

File: host/xtest/regression_1000.c (hunk 1 above)
Comment (ruchi393) [reply host/xtest/regression_1000.c:2666]: Thanks. To maintain consistency with the other error for this testcase, will remove Do_ADBG_EndSubCase from here.

File: ta/os_test/pauth_a64.S [hunk 9]
```diff
@@ -5,9 +5,17 @@
 
 #include <asm.S>
 
+
```
Comment (etienne-lms) [inline ta/os_test/pauth_a64.S:8]: remove extra empty line

File: ta/os_test/ta_arm_pauth.c [hunk 10]
```diff
@@ -32,11 +37,8 @@ TEE_Result ta_entry_pauth_test_nop(void)
...
 	/* Check if PAC instruction generates the authentication code */
-	for (int i = 0; i < 10; i++) {
-		asm volatile("paciza %0 " : "+r" (ptr));
-		pac |= ptr & VA_MASK;
-		ptr = i;
-	}
+	for (int i = 0; i < 10; i++)
+		pac |= sign_using_keyia(i) & VA_MASK;
 
 	if (implemented && pac)
```
Comment (etienne-lms) [inline ta/os_test/ta_arm_pauth.c:43]: Should `pac != 0 ` be checked for each of the _paciza_ instructions in the loop above?

Comment (ruchi393) [reply ta/os_test/ta_arm_pauth.c:43]: I intentionally didn't add this check. Here we are assuming VA_MASK with 48 bits of VA. Since the VA MASK used over here is not exact, there are minimal chances that authentication code generated may be 0 for the mask used. Hence I repeated it over a range of numbers and ored the result. 

The main purpose of this test case is basically to ensure that pac is enabled and these instructions are not treated as nops.

File: ta/os_test/sub.mk [hunk 11]
```diff
@@ -20,3 +20,11 @@ cxxflags-remove-cxx_tests.cpp-y += -pg
 srcs-y += cxx_tests_c.c
 cflags-remove-cxx_tests_c.c-y += -pg
 endif
+
+ifeq ($(sm),ta_arm64)
```
Comment (jenswi-linaro) [inline ta/os_test/sub.mk:24]: Depending on `CFG_TA_PAUTH` being `y` should be enough.

File: ta/os_test/sub.mk [hunk 12]
```diff
@@ -20,3 +20,11 @@ cxxflags-remove-cxx_tests.cpp-y += -pg
...
+srcs-$(CFG_TA_PAUTH) += pauth_a64.S
+srcs-$(CFG_TA_PAUTH) += ta_arm_pauth.c
+# -march=armv8.3-a enables the non-nops instructions for PAC. We are using one
+#  such instruction in the PAC test.
+cflags-$(CFG_TA_PAUTH) += -march=armv8.3-a
```
Comment (jenswi-linaro) [inline ta/os_test/sub.mk:29]: Why isn't this always added to `ta_arm64-platform-cflags` when `CFG_TA_PAUTH` is `y`?

Comment (ruchi393) [reply ta/os_test/sub.mk:29]: The instructions paciasp and aut which are used by compiler when CFG_TA_PAUTH is y are nop instructions. Using them without -march=armv8.3-a doesn't return a compilation error. While the instruction PACIZA used in the testcase here is a non-nop instruction for which the flag armv8.3-a needs to be enabled. If in future we start using non-nop PAuth instruction in TEE, we can introduce the cflag.

Comment (jenswi-linaro) [reply ta/os_test/sub.mk:29]: I don't understand why the TA itself is supposed to keep track of these flags. I'd expect the TA dev-kit to do that.

Comment (ruchi393) [reply ta/os_test/sub.mk:29]: I can add it to the ta dev-kit if you think that would be the right place. This is not required usually for TA's using PAuth. It is only required if TA's explicitly use a non-nop PAuth instruction using assembly/inline assembly.

Comment (ruchi393) [reply ta/os_test/sub.mk:29]: With -mbranch-protection , paciasp and autiasp instructions are added as needed. These instructions are treated as nops when they are executed on architectures < v8.3. So compiler doesn't complain when you use these instructions. However instruction paciza is a non-nop instruction, so if it is being used it won't work on architectures < v8.3 i.e won't be treated as nops. So compiler complains for these instructions without explicit -march flag.

Ideally it would be good to have -march flag specified, however this should be driven by the platform port.

File: ta/os_test/sub.mk (hunk 11 above)
Comment (ruchi393) [reply ta/os_test/sub.mk:24]: Ok.

How's the sm set to ta_arm64 ? I tried using CFG_USER_TA_TARGETS=ta_arm32, but that doesn't seem to set this. i remember this worked when i had tested the same with BTI.

Comment (jenswi-linaro) [reply ta/os_test/sub.mk:24]: In `export-ta_arm64/mk/conf.mk`. You select the devkit correspondingly.

Comment (ruchi393) [reply ta/os_test/sub.mk:24]: Only CFG_TA_PAUTH is not enough.  PAC would work only with arm64 TA's. If we compile with COMPILE_S_USER=32, issues will be observed in compilation.

Comment (jenswi-linaro) [reply ta/os_test/sub.mk:24]: It seems a bit strange to have a feature enabled which isn't supported even at build time.
But there isn't much we can do about that here. Let's keep it as it is for now.

Comment (ruchi393) [reply ta/os_test/sub.mk:24]: Yes, we did discuss this when BTI was being added. This seemed the most feasible solution.

**Comment by ruchi393** [comment]
Should I squash the patches ?

**Comment by jenswi-linaro** [comment]
> Should I squash the patches ?

Please do.

**Comment by ruchi393** [comment]
All review commits have been squashed together, @jenswi-linaro , @etienne-lms please have a ook

**Review by jenswi-linaro — COMMENTED** [review]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by ruchi393** [comment]
Thanks, PR updated with A-by tag

**Comment by jforissier** [comment]
@etienne-lms any feedback?
