### PR TITLE
xtest: pkcs11: keep the X.509 subject and issuer names const

### PR DESCRIPTION
**Pull request by ricardosalveti**
OpenSSL 4.0 changed X509_get_subject_name() and X509_get_issuer_name() to return a const X509_NAME pointer. The certificate test assigns the results to non-const pointers, and since xtest builds with -Werror the whole host build fails against OpenSSL 4.0:

  pkcs11_1000.c:7879:27: error: assignment discards 'const' qualifier
  from pointer target type [-Werror=discarded-qualifiers]

Declare both names const. They are only passed to i2d_X509_NAME(), which has taken a const pointer since OpenSSL 1.1.0, and to ADBG_EXPECT_NOT_NULL(), which takes a const void pointer, so the change builds unchanged against OpenSSL 3.x as well.

### CODE REVIEW

**Comment by ricardosalveti** [comment]
Failed tests to be fixed by https://github.com/OP-TEE/optee_test/pull/839

**Comment by jenswikl** [comment]
`Acked-by: Jens Wiklander <jens.wiklander@oss.qualcomm.com>`

**Comment by jenswikl** [comment]
Please apply the tag.

**Comment by ricardosalveti** [comment]
Tag applied!
