### ISSUE TITLE
Question about building optee_test with aarch64-linux-android

### ISSUE THREAD

**Issue by shumeigiku** [OP-TEE/optee_test#619]
Hi all,

I am trying to build optee_test on Android kernel. The source code of OPTEE_OS and OPTEE_CLIENT are downloaded from arm reference platforms, and they are successfully built and packaged. I can boot them on my device. The kernel is Linux v4.14.

But the arm reference platform does not provide the source of OPTEE_TEST. So, I must download it from here and build it. I select OPTEE_TEST v2.5 (also I try to build with v3.0) and the cross-compile is aarch64-linux-android, n21.

My build scripts are as follows:

```
cd optee-test
export CROSS_COMPILE=aarch64-linux-android-
export TA_DEV_KIT_DIR=optee_os/out/arm-plat-vexpress/export-ta_arm64
export OPTEE_OS_PATH=optee_os
export OPTEE_CLIENT_EXPORT=optee_client/out/export/usr
make
```

Since I only interest in **aes-perf** and **sha-perf**, and due to some bugs (e.g., ```unknown type name 'pthread_barrier_t' ```), I modify the Makefile in ```optee-test/host/xtest``` by removing the regression_1000 - regression_9000 benchmarks, and remove the code related to "pthread_barrier_t". I only build the **aes-perf** and **sha-perf**.

However, I face two problems in building:
(1) If I build, the error is:
```
... 
LD      optee_test-2.5.0/out/xtest/xtest
aarch64-linux-android/bin/ld: cannot find -lpthread
clang90: error: linker command failed with exit code 1 (use -v to see invocation)
Makefile:137: recipe for target 'xtest' failed
...
```
(2) If I change the **-lpthread** as **-pthread** in ```optee-test/host/xtest/Makefile```, it says
```
aarch64-linux-android/bin/ld: warning: libpthread.so.0, needed by optee_client/out/export/usr/lib/libteec.so, not found (try using -rpath or -rpath-link)
aarch64-linux-android/bin/ld: warning: libc.so.6, needed by optee_client/out/export/usr/lib/libteec.so, not found (try using -rpath or -rpath-link)
optee_client/out/export/usr/lib/libteec.so: undefined reference to `open64@GLIBC_2.17'
optee_client/out/export/usr/lib/libteec.so: undefined reference to `pthread_mutex_unlock@GLIBC_2.17'
optee_client/out/export/usr/lib/libteec.so: undefined reference to `__errno_location@GLIBC_2.17'
optee_client/out/export/usr/lib/libteec.so: undefined reference to `syscall@GLIBC_2.17'
...
(I do not list the remaining undefined reference here)
...
clang90: error: linker command failed with exit code 1 (use -v to see invocation)
Makefile:146: recipe for target 'xtest' failed
```

What should I do? Can someone help me?

Sincerely,
Shumeigiku

**Comment by shumeigiku** [comment]
When I try to make OP-TEE with ```aarch64-linux-gnu-gcc```, it **seems** to work.
I run ```make install``` and get (1) /bin/xtest, (2) /lib/optee_armtz/*.ta 
I use Juno R2 development board, so I run adb to copy them into ```/vendor/bin/xtest``` and ```/vendor/lib/optee_armtz/```
However when I run ```xtest``` in Juno's terminal, it reports 
```
/system/bin/sh: /vendor/bin/xtest: No such file or directory 
```
But it exists in my /vendor, here is the result when I running ```ls -l``` in /vendor/bin

```
...
lrwxr-xr-x 1 root shell     13 2019-02-13 21:26 tee -> toybox_vendor
-rwxr-xr-x 1 root shell  68864 2019-02-13 21:16 tee-supplicant
...
-rwxrwxrwx 1 root shell 303256 2022-10-10 15:37 xtest
...
```

Does it mean that I must use aarch64-linux-android to compile? If not, what is the correct way to install xtest and TAs?

**Comment by jforissier** [comment]
> /system/bin/sh: /vendor/bin/xtest: No such file or directory 

Some shared library may be missing. Check `aarch64-linux-gnu-readelf -d xtest | grep NEEDED`.

**Comment by shumeigiku** [comment]
> > /system/bin/sh: /vendor/bin/xtest: No such file or directory
> 
> Some shared library may be missing. Check `aarch64-linux-gnu-readelf -d xtest | grep NEEDED`.

Many thanks, it did lack some libs.
Same as previous question, when I compile with aarch64-linux-android, I need to call ```-Wl,-rpath-link=xxxx``` to link these lib.so, and upload them into my Juno.

I would like to close this question.
